
spring.application.name=credito-service
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres-credito:5432/creditodb
spring.datasource.username=credito
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
